title: "This is Peiyuan"
locale: "zh-CN"

image_cdn: ""

theme: minimal-mistakes-jekyll

date_format: "%Y年%-m月%-d日"

collections:
  essays:
    output: true
    permalink: /essays/:year/:slug/

exclude:
  - temp

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
